### ISSUE TITLE
The referenced project '..\XiaomiWatch.Common\XiaomiWatch.Common.csproj' does not exist.

### ISSUE THREAD

**Issue by TheSainEyereg** [m0tral/UnpackMiColorFace#2]
I tried to build the project using `msbuild` and `dotnet build` but each time I got an error that the project `XiaomiWatch.Common` is not found. Did you forget to specify some dependencies?

**Comment by Doliman100** [comment]
1. Unfold **UnpackMiColorFace > References**
2. Remove XiaomiWatch.Common
3. Press RMB on **References** and select **Add Reference...**
4. Press **Browse...** button at the right bottom corner of the window.
5. Add "UnpackMiColorFace-master/lib/XiaomiWatch.Common.dll" file.
6. Mark XiaomiWatch.Common.dll with a check.
7. Press **OK**.
8. Now you can build the solution.
