### ISSUE TITLE
xiaomiwatch.common.dll, spec and compiler source

### ISSUE THREAD

**Issue by Chriz76** [m0tral/UnpackMiColorFace#5]
Hello @m0tral ,

Where did you get the xiaomiwatch.common.dll and is there any spec for the watch face packed file format and for the watch faces like supported datasources, etc.

And do you have the source code for the compiler? Otherwise I would have to try to reengineer it from the unpacker.

Thanks!

**Comment by m0tral** [comment]
Wrote, I won't include sources)) You may decompile, np
