### ISSUE TITLE
failed to unpack

### ISSUE THREAD

**Issue by lvPokka** [m0tral/UnpackMiColorFace#6]
Failed to uplack, image type = 0

[bad-wface.zip](https://github.com/user-attachments/files/16483159/bad-wface.zip)

2 more
[encodig_problem.zip](https://github.com/user-attachments/files/16513668/encodig_problem.zip)

**Comment by lvPokka** [comment]
type = 3 

24 bit bmp header required in ConvertToBmpGTRv2

**Comment by m0tral** [comment]
which watch?

**Comment by lvPokka** [comment]
mi band 9, but looks like this watchface is for miband8

**Comment by m0tral** [comment]
nope, looks like wf is for mb9, images are indexed8bit RGBA, need to update decode/encode code
will test today

**Comment by m0tral** [comment]
done in v4.15
