### ISSUE TITLE
Please fix unpacking MiBand 9

### ISSUE THREAD

**Issue by mak7im01** [m0tral/UnpackMiColorFace#7]
Hi. Unpacking of dials Mi Band 9 in most cases occurs with errors. Also the images are broken.
```
в XiaomiWatch.Common.BinaryExtender.GetWord(Byte[] data, UInt32 offset, UInt32 bigEndian)
   в UnpackMiColorFace.Decompiler.FaceV2Decompiler.ProcessImageSingle(WatchType watchType, Byte[] data, UInt32 offset, String path)
image processing err: System.ArgumentException: Длина исходного массива недостаточна. Проверьте значения srcIndex и длины, а также нижние границы массива.
   в System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   в System.Array.Copy(Array sourceArray, Int64 sourceIndex, Array destinationArray, Int64 destinationIndex, Int64 length)
   в XiaomiWatch.Common.BinaryExtender.GetWord(Byte[] data, UInt32 offset, UInt32 bigEndian)
   в UnpackMiColorFace.Decompiler.FaceV2Decompiler.ProcessImageSingle(WatchType watchType, Byte[] data, UInt32 offset, String path)
image processing err: System.ArgumentException: Длина исходного массива недостаточна. Проверьте значения srcIndex и длины, а также нижние границы массива.
   в System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   в System.Array.Copy(Array sourceArray, Int64 sourceIndex, Array destinationArray, Int64 destinationIndex, Int64 length
```)

**Comment by mak7im01** [comment]
> Hi. Unpacking of dials Mi Band 9 in most cases occurs with errors. Also the images are broken.
> 
> ```
> в XiaomiWatch.Common.BinaryExtender.GetWord(Byte[] data, UInt32 offset, UInt32 bigEndian)
>    в UnpackMiColorFace.Decompiler.FaceV2Decompiler.ProcessImageSingle(WatchType watchType, Byte[] data, UInt32 offset, String path)
> image processing err: System.ArgumentException: Длина исходного массива недостаточна. Проверьте значения srcIndex и длины, а также нижние границы массива.
>    в System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
>    в System.Array.Copy(Array sourceArray, Int64 sourceIndex, Array destinationArray, Int64 destinationIndex, Int64 length)
>    в XiaomiWatch.Common.BinaryExtender.GetWord(Byte[] data, UInt32 offset, UInt32 bigEndian)
>    в UnpackMiColorFace.Decompiler.FaceV2Decompiler.ProcessImageSingle(WatchType watchType, Byte[] data, UInt32 offset, String path)
> image processing err: System.ArgumentException: Длина исходного массива недостаточна. Проверьте значения srcIndex и длины, а также нижние границы массива.
>    в System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
>    в System.Array.Copy(Array sourceArray, Int64 sourceIndex, Array destinationArray, Int64 destinationIndex, Int64 length
> ```)
![w v1 2_preview](https://github.com/user-attachments/assets/3d5fa71f-cb78-4460-991b-461a1734b138)

> 
> Dial example:
> [v1.2.zip](https://github.com/user-attachments/files/16637201/v1.2.zip)
> ```

**Comment by mak7im01** [comment]
![w v1 2_preview](https://github.com/user-attachments/assets/1355bd57-1129-4cb7-8893-27e2b74568ee)
Dial example:
[v1.2.zip](https://github.com/user-attachments/files/16637227/v1.2.zip)

**Comment by m0tral** [comment]
Да, ок, проверю

**Comment by m0tral** [comment]
done in new v4.15
