### ISSUE TITLE
Can't unpack watchface 

### ISSUE THREAD

**Issue by qimlisky** [m0tral/UnpackMiColorFace#8]
Watch detected: MiBand8
got compressed image[images:1]: 0000522C, type:01, rle:10
got compressed image[images:2]: 000088B7, type:01, rle:10
got compressed imageList[images:0]: 00041E2F, type:04, rle:10
got compressed imageList[images:1]: 0004498D, type:04, rle:10
got compressed imageList[images:2]: 0004667F, type:04, rle:10
got compressed imageList[images:3]: 00048E96, type:04, rle:10
got compressed imageList[images:4]: 000559B3, type:04, rle:10
got compressed imageList[images:5]: 00056873, type:04, rle:10
got compressed imageList[images:6]: 00059589, type:04, rle:10
got compressed imageList[images:7]: 0005A77B, type:04, rle:10
action processing err: System.ArgumentException: 源数组长度不足。请检查 srcIndex 和长度以及数组的下限。
   在 System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   在 System.Array.Copy(Array sourceArray, Int64 sourceIndex, Array destinationArray, Int64 destinationIndex, Int64 length)
   在 XiaomiWatch.Common.BinaryExtender.GetDWord(Byte[] data, UInt32 offset, UInt32 bigEndian)
   在 UnpackMiColorFace.Decompiler.FaceV2Decompiler.ProcessAction(Byte[] data, UInt32 offset, String path)
action processing err: System.ArgumentException: 源数组长度不足。请检查 srcIndex 和长度以及数组的下限。
   在 System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   在 System.Array.Copy(Array sourceArray, Int64 sourceIndex, Array destinationArray, Int64 destinationIndex, Int64 length)
   在 XiaomiWatch.Common.BinaryExtender.GetDWord(Byte[] data, UInt32 offset, UInt32 bigEndian)
   在 UnpackMiColorFace.Decompiler.FaceV2Decompiler.ProcessAction(Byte[] data, UInt32 offset, String path)
System.ArgumentException: 路径中具有非法字符。
   在 System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   在 System.IO.Path.InternalGetDirectoryName(String path)
   在 UnpackMiColorFace.Decompiler.FaceV2Decompiler.ProcessAppData(WatchType watchType, Byte[] data, UInt32 offset)
   在 UnpackMiColorFace.Decompiler.FaceV2Decompiler.Process(WatchType watchType, Byte[] data)
   在 UnpackMiColorFace.Unpacker.Exec(String filename)
   在 UnpackMiColorFace.Program.MainBody(String[] args)
Got unexcepted error,
Please check a source file is correct Watchface

This watch face is intended for use on MB9, but I noticed that he chose MB8. Is it a problem with my watch face file? However, it does work on MB9, which is the Chinese version.

**Comment by m0tral** [comment]
Seems you use an outdated version of unpacker or your watchfaces is unoriginal, and packed with wrong ID, because why unpacker can't detect it right.

**Comment by qimlisky** [comment]
My watchface is indeed not official, it's from a third-party source. Is there any way to unpack this third-party watch face?

**Comment by m0tral** [comment]
done in new v4.15

**Comment by qimlisky** [comment]
but new version have same problem.Can adding the device type that watchface is compatible with avoid this problem


Watch detected: MiBand8
got compressed image[images:1]: 0000522C, type:01, rle:10
got compressed image[images:2]: 000088B7, type:01, rle:10
got compressed imageList[images:0]: 00041E2F, type:04, rle:10
got compressed imageList[images:1]: 0004498D, type:04, rle:10
got compressed imageList[images:2]: 0004667F, type:04, rle:10
got compressed imageList[images:3]: 00048E96, type:04, rle:10
got compressed imageList[images:4]: 000559B3, type:04, rle:10
got compressed imageList[images:5]: 00056873, type:04, rle:10
got compressed imageList[images:6]: 00059589, type:04, rle:10
got compressed imageList[images:7]: 0005A77B, type:04, rle:10
action processing err: System.ArgumentException: 源数组长度不足。请检查 srcIndex 和长度以及数组的下限。
   在 System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   在 System.Array.Copy(Array sourceArray, Int64 sourceIndex, Array destinationArray, Int64 destinationIndex, Int64 length)
   在 UnpackMiColorFace.Decompiler.FaceV2Decompiler.ProcessAction(Byte[] data, UInt32 offset, String path)
action processing err: System.ArgumentException: 源数组长度不足。请检查 srcIndex 和长度以及数组的下限。
   在 System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   在 System.Array.Copy(Array sourceArray, Int64 sourceIndex, Array destinationArray, Int64 destinationIndex, Int64 length)
   在 UnpackMiColorFace.Decompiler.FaceV2Decompiler.ProcessAction(Byte[] data, UInt32 offset, String path)
System.ArgumentException: 路径中具有非法字符。
   在 System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   在 System.IO.Path.InternalGetDirectoryName(String path)
   在 UnpackMiColorFace.Decompiler.FaceV2Decompiler.ProcessAppData(WatchType watchType, Byte[] data, UInt32 offset)
   在 UnpackMiColorFace.Decompiler.FaceV2Decompiler.Process(WatchType watchType, Byte[] data)
   在 UnpackMiColorFace.Unpacker.Exec(String filename)
   在 UnpackMiColorFace.Program.MainBody(String[] args)
Got unexcepted error,
Please check a source file is correct Watchface

**Comment by m0tral** [comment]
Use prev release to unpack MiBand 8,
current has code improvement which broke prev models unpacking, didn't tested well yet.
Will be fixed in next release

**Comment by qimlisky** [comment]
Sorry, I mean is the watchface(.bin) I want to unpack is used on mb9, but the software recognizes mb8.I want to successfully unpack mb9 watchface.but unsuccessful

**Comment by m0tral** [comment]
That means in watchface is not set proper ID, unpacker detects it that way, cuz there is no difference between mb8 and mb9,
change ID start chars to 366, i.e. 0x333636

**Comment by qimlisky** [comment]
but successful unpack some source![IMG_20240824_211120.jpg](https://github.com/user-attachments/assets/57e74941-e2d2-4248-9242-1e1fc974bf39)

this watchface should have 8 image folders.But only one was successfully unpacked.this watchface have 8 styles.![IMG_20240824_211802.jpg](https://github.com/user-attachments/assets/92d364a0-b8e0-4ce9-bdeb-0833c30b6199)

**Comment by qimlisky** [comment]
maby my mb9 watchface have problem.Do you want me to give you the file?

**Comment by m0tral** [comment]
I have access to all models stock watchfaces.
